# Generated by Django 6.0 on 2025-12-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'in_progress'), ('DONE', 'done'), ('TODO', 'todo')], default='TODO', max_length=20),
        ),
    ]
