# Generated by Django 6.0 on 2025-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DONE', 'done'), ('IN_PROGRESS', 'in_progress'), ('TODO', 'todo')], default='TODO', max_length=20),
        ),
    ]
