# Generated by Django 6.0 on 2025-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DONE', 'done'), ('TODO', 'todo'), ('IN_PROGRESS', 'in_progress')], default='TODO', max_length=20),
        ),
    ]
