# Generated by Django 6.0 on 2025-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_task_description_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('todo', 'Todo'), ('in_progress', 'In progress')], default='todo', max_length=20),
        ),
    ]
