# Generated by Django 6.0 on 2025-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_task_description_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
