# Generated by Django 6.0 on 2025-12-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
